name: Laravel Tests

on:
  push:
    branches:
      - develop  # Cambia por la rama principal de tu proyecto
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.6'  # Ajusta la versión de PHP según tu proyecto

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

      - name: Create test database
        run: php artisan test:prepare

      - name: Run tests
        run: php artisan test
